Update PD.js
milesdbader/agent_based_morality pull request #5
Opened 2022-05-07 22:33 UTC by GCopoulos

Added updated reputation code.

Reputation Change code in PlayOneGame function
Skip game based on reputation in PlayRepeatedGame

The variables concerning the reputation threshold and error rate are in PD under Tournament Agent (separate pull request)

2022-05-08 05:19 UTC, milesdbader requested changes
yeahhh this is suuper solid and pretty straight forward–I agree, there's not a log of testing to do here of the framework as long as it's not generating any clear errors–check out that one change and lmk what you think but otherwise I think we're all set here.

We'll have to figure out what we want to use this for–as that'll dictate things like line 110. Right now, I'm not sold on the repErrorRate being super useful (kinda feels like overcomplicating the model but hard to say, it definitely does have some parallels in real life). But otherwise makes a ton of sense. I'm in favor of a global threshold personally, but there's def room to experiment w both.

2022-05-08 23:12 UTC, GCopoulos reviewed
Made the requested changes - changed the early "return scores" to "continue" as that's what is necessary to still play the other games in the set of 10. Lmk if you see anything else problematic.

2022-05-08 23:13 UTC, GCopoulos reviewed
Fixed an issue where I forgot to specify "agents" as an argument for PlayOneGame

2022-05-09 21:33 UTC, milesdbader approved these changes

2022-05-09 21:35 UTC, merged